## 5.2-3

In [1]:
import numpy as np

In [ ]:
A = [[-1.341,  0.9933, 0, -0.1689, -0.2518], # alpha
     [43.223, -0.8693, 0, -17.251, -1.5766], # q
     [ 1.341,  0.0067, 0,  0.1689,  0.2518], # gamma
     [ 0.000,  0.0000, 0, -20.000,  0.0000], # de
     [ 0.000,  0.0000, 0,  0.0000, -20.000],] # df

B = [[0,  0],
     [0,  0],
     [0,  0],
     [20, 0],
     [0, 20],]

In [3]:
l, v = np.linalg.eig(A)
print(l)
print(v)

[  0.          5.4514521  -7.6617521 -20.        -20.       ]
[[ 0.          0.14459894  0.15519008 -0.03126534  0.01033342]
 [ 0.          0.98880635 -0.98753452  0.70738415  0.05891038]
 [ 1.          0.03678509 -0.02629861 -0.00410386 -0.01327894]
 [ 0.          0.          0.          0.70612556  0.        ]
 [ 0.          0.          0.          0.          0.99812146]]


In [ ]:
C = [[0, 1, 0, 0, 0],
     [47.76, -0.268, 0, -4.56, 4.45],
     [0, 0, 1, 0, 0],
     [0, 0, 0, 1, 0],
     [0, 0, 0, 0, 1],]

In [ ]:
D1 = [[1, 0, 0, 0, 0],
      [0, 1, 0, 0, 0],
      [0, 0, 1, 0, 0]]

eigstruct = [[-1.341,  0.9933, 0, -0.1689, -0.2518, 0, 0, 0], # alpha
             [43.223, -0.8693, 0, -17.251, -1.5766, 0, 0, 0], # q
             [ 1.341,  0.0067, 0,  0.1689,  0.2518, 0, 0, 0], # gamma
             [ 0.000,  0.0000, 0, -20.000,  0.0000, 20, 0, 0], # de
             [ 0.000,  0.0000, 0,  0.0000, -20.000, 0, 20, 0],
             [1, 0, 0, 0, 0, 0, 0, 0],
             [0, 1, 0, 0, 0, 0, 0, 0],
             [0, 0, 1, 0, 0, 0, 0, 0],]

Ae = np.array(eigstruct)
np.linalg.inv(Ae)

LinAlgError: Singular matrix

In [23]:
l1 = -5.6 + 4.2j
l1*np.eye(5) - np.array(A)

array([[-4.2590e+00+4.2j, -9.9330e-01+0.j , -0.0000e+00+0.j ,
         1.6890e-01+0.j ,  2.5180e-01+0.j ],
       [-4.3223e+01+0.j , -4.7307e+00+4.2j, -0.0000e+00+0.j ,
         1.7251e+01+0.j ,  1.5766e+00+0.j ],
       [-1.3410e+00+0.j , -6.7000e-03+0.j , -5.6000e+00+4.2j,
        -1.6890e-01+0.j , -2.5180e-01+0.j ],
       [-0.0000e+00+0.j , -0.0000e+00+0.j , -0.0000e+00+0.j ,
         1.4400e+01+4.2j, -0.0000e+00+0.j ],
       [-0.0000e+00+0.j , -0.0000e+00+0.j , -0.0000e+00+0.j ,
        -0.0000e+00+0.j ,  1.4400e+01+4.2j]])